export type AdminMenuSeedNode = {
  title: string;
  icon?: string | null;
  path?: string | null;
  requiredPermissions?: string[];
  children?: AdminMenuSeedNode[];
};

// Mirrors the built-in menu structure in frontend/src/layouts/AdminLayout.tsx
// Icons are stored as string keys (e.g. FaCog) and mapped on the frontend.
export const DEFAULT_ADMIN_MENU: AdminMenuSeedNode[] = [
  { title: 'Dashboard', icon: 'FaTachometerAlt', path: '/admin/dashboard' },
  {
    title: 'Products',
    icon: 'FaBoxes',
    children: [
      { title: 'All Products', icon: 'FaBoxes', path: '/admin/products', requiredPermissions: ['view-products'] },
      { title: 'Manage Categories', icon: 'FaBoxes', path: '/admin/categories', requiredPermissions: ['manage-categories'] },
      { title: 'Combo Products', icon: 'FaBoxes', path: '/admin/combo-products', requiredPermissions: ['view-products'] },
      {
        title: 'Deal of the Day',
        icon: 'FaBoxes',
        path: '/admin/products/deal-of-the-day',
        requiredPermissions: ['manage-discounts', 'edit-products'],
      },
      { title: 'Offers & Promotions', icon: 'FaBoxes', path: '/admin/offers', requiredPermissions: ['manage-discounts'] },
      { title: 'Special Offers', icon: 'FaBoxes', path: '/admin/special-offers', requiredPermissions: ['manage-discounts'] },
    ],
  },
  {
    title: 'Sales',
    icon: 'FaShoppingCart',
    children: [
      { title: 'Orders', icon: 'FaShoppingCart', path: '/admin/sales', requiredPermissions: ['view-sales-orders'] },
      {
        title: 'Incomplete Order',
        icon: 'FaShoppingCart',
        path: '/admin/sales/incomplete-orders',
        requiredPermissions: ['view-sales-orders'],
      },
      {
        title: 'Late Delivery',
        icon: 'FaShoppingCart',
        path: '/admin/sales/late-delivery',
        requiredPermissions: ['view-sales-orders'],
      },
    ],
  },
  {
    title: 'Reports',
    icon: 'FaChartBar',
    children: [
      {
        title: 'Overview',
        icon: 'FaChartBar',
        path: '/admin/reports?tab=overview',
        requiredPermissions: [
          'view-sales-reports',
          'view-product-reports',
          'view-stock-reports',
          'view-crm-reports',
          'view-financial-reports',
          'view-marketing-reports',
          'view-mlm-reports',
          'view-hr-reports',
          'view-recruitment-reports',
        ],
      },
      { title: 'Sales Reports', icon: 'FaChartBar', path: '/admin/reports?tab=sales', requiredPermissions: ['view-sales-reports'] },
      {
        title: 'Customer Reports',
        icon: 'FaChartBar',
        path: '/admin/reports?tab=customers',
        requiredPermissions: ['view-crm-reports', 'view-customers'],
      },
      { title: 'Product Reports', icon: 'FaChartBar', path: '/admin/reports?tab=products', requiredPermissions: ['view-product-reports'] },
      {
        title: 'Inventory Reports',
        icon: 'FaChartBar',
        path: '/admin/reports?tab=inventory',
        requiredPermissions: ['view-stock-reports'],
      },
      {
        title: 'Marketing Reports',
        icon: 'FaChartBar',
        path: '/admin/reports?tab=marketing',
        requiredPermissions: ['view-marketing-reports'],
      },
    ],
  },
  { title: 'Customers', icon: 'FaUsers', path: '/admin/customers', requiredPermissions: ['view-customers'] },
  {
    title: 'Loyalty',
    icon: 'FaGift',
    requiredPermissions: ['view-mlm-reports', 'manage-mlm-settings'],
    children: [
      { title: 'Dashboard', icon: 'FaTachometerAlt', path: '/admin/loyalty' },
      { title: 'Members', icon: 'FaUsers', path: '/admin/loyalty/members' },
      { title: 'Referrals', icon: 'FaGift', path: '/admin/loyalty/referrals' },
      { title: 'Campaigns', icon: 'FaBullseye', path: '/admin/loyalty/referrals/campaigns' },
      { title: 'Partners', icon: 'FaHandshake', path: '/admin/loyalty/referrals/partners' },
      { title: 'Subscriptions', icon: 'FaShoppingCart', path: '/admin/loyalty/subscriptions' },
    ],
  },
  {
    title: 'Tagging',
    icon: 'FaTags',
    requiredPermissions: ['customer-segmentation', 'view-products'],
    children: [
      { title: 'Manage Tags', icon: 'FaTags', path: '/admin/tagging?tab=manage' },
      { title: 'Tagwise Filter', icon: 'FaTags', path: '/admin/tagging?tab=filter' },
    ],
  },
  { title: 'Inventory', icon: 'FaWarehouse', path: '/admin/inventory', requiredPermissions: ['view-inventory'] },
  { title: 'Purchase', icon: 'FaShoppingBag', path: '/admin/purchase', requiredPermissions: ['view-purchase-orders'] },
  {
    title: 'HR Management',
    icon: 'FaUserTie',
    requiredPermissions: ['view-employees', 'manage-attendance', 'process-payroll', 'view-hr-reports'],
    children: [
      { title: 'Branches', icon: 'FaUserTie', path: '/admin/hrm/branches' },
      { title: 'Departments', icon: 'FaUserTie', path: '/admin/hrm/departments' },
      { title: 'Designations', icon: 'FaUserTie', path: '/admin/hrm/designations' },
      { title: 'Document Types', icon: 'FaUserTie', path: '/admin/hrm/document-types' },
      { title: 'Employees', icon: 'FaUserTie', path: '/admin/hrm/employees' },
      { title: 'Award Types', icon: 'FaUserTie', path: '/admin/hrm/award-types' },
      { title: 'Awards', icon: 'FaUserTie', path: '/admin/hrm/awards' },
      { title: 'Promotions', icon: 'FaUserTie', path: '/admin/hrm/promotions' },
      { title: 'Resignations', icon: 'FaUserTie', path: '/admin/hrm/resignations' },
      { title: 'Terminations', icon: 'FaUserTie', path: '/admin/hrm/terminations' },
      { title: 'Warnings', icon: 'FaUserTie', path: '/admin/hrm/warnings' },
      { title: 'Trips', icon: 'FaUserTie', path: '/admin/hrm/trips' },
      { title: 'Complaints', icon: 'FaUserTie', path: '/admin/hrm/complaints' },
      { title: 'Transfers', icon: 'FaUserTie', path: '/admin/hrm/transfers' },
      { title: 'Holidays', icon: 'FaUserTie', path: '/admin/hrm/holidays' },
      { title: 'Announcements', icon: 'FaUserTie', path: '/admin/hrm/announcements' },
      {
        title: 'Training Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Training Types', icon: 'FaUserTie', path: '/admin/hrm/training-management/training-types' },
          { title: 'Training Programs', icon: 'FaUserTie', path: '/admin/hrm/training-management/training-programs' },
          { title: 'Training Sessions', icon: 'FaUserTie', path: '/admin/hrm/training-management/training-sessions' },
          { title: 'Employee Trainings', icon: 'FaUserTie', path: '/admin/hrm/training-management/employee-trainings' },
        ],
      },
      {
        title: 'Performance Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Indicator Categories', icon: 'FaUserTie', path: '/admin/hrm/performance-management/indicator-categories' },
          { title: 'Indicators', icon: 'FaUserTie', path: '/admin/hrm/performance-management/indicators' },
          { title: 'Goal Types', icon: 'FaUserTie', path: '/admin/hrm/performance-management/goal-types' },
          { title: 'Employee Goals', icon: 'FaUserTie', path: '/admin/hrm/performance-management/employee-goals' },
          { title: 'Review Cycles', icon: 'FaUserTie', path: '/admin/hrm/performance-management/review-cycles' },
          { title: 'Employee Reviews', icon: 'FaUserTie', path: '/admin/hrm/performance-management/employee-reviews' },
        ],
      },
      {
        title: 'Attendance Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Shifts', icon: 'FaUserTie', path: '/admin/hrm/attendance-management/shifts' },
          { title: 'Attendance Policies', icon: 'FaUserTie', path: '/admin/hrm/attendance-management/attendance-policies' },
          { title: 'Attendance Records', icon: 'FaUserTie', path: '/admin/hrm/attendance-management/attendance-records' },
          { title: 'Regularizations', icon: 'FaUserTie', path: '/admin/hrm/attendance-management/regularizations' },
        ],
      },
      {
        title: 'Payroll',
        icon: 'FaUserTie',
        children: [
          { title: 'Salary Components', icon: 'FaUserTie', path: '/admin/hrm/payroll/salary-components' },
          { title: 'Employee Salaries', icon: 'FaUserTie', path: '/admin/hrm/payroll/employee-salaries' },
          { title: 'Payroll Runs', icon: 'FaUserTie', path: '/admin/hrm/payroll/payroll-runs' },
          { title: 'Payslips', icon: 'FaUserTie', path: '/admin/hrm/payroll/payslips' },
        ],
      },
      {
        title: 'Leave Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Leave Types', icon: 'FaUserTie', path: '/admin/hrm/leave-management/leave-types' },
          { title: 'Leave Policies', icon: 'FaUserTie', path: '/admin/hrm/leave-management/leave-policies' },
          { title: 'Leave Applications', icon: 'FaUserTie', path: '/admin/hrm/leave-management/leave-applications' },
          { title: 'Leave Balances', icon: 'FaUserTie', path: '/admin/hrm/leave-management/leave-balances' },
        ],
      },
      {
        title: 'Recruitment',
        icon: 'FaUserTie',
        children: [
          { title: 'Job Categories', icon: 'FaUserTie', path: '/admin/hrm/recruitment/job-categories' },
          { title: 'Job Requisitions', icon: 'FaUserTie', path: '/admin/hrm/recruitment/job-requisitions' },
          { title: 'Job Types', icon: 'FaUserTie', path: '/admin/hrm/recruitment/job-types' },
          { title: 'Job Locations', icon: 'FaUserTie', path: '/admin/hrm/recruitment/job-locations' },
          { title: 'Job Postings', icon: 'FaUserTie', path: '/admin/hrm/recruitment/job-postings' },
          { title: 'Candidate Sources', icon: 'FaUserTie', path: '/admin/hrm/recruitment/candidate-sources' },
          { title: 'Candidates', icon: 'FaUserTie', path: '/admin/hrm/recruitment/candidates' },
          { title: 'Interview Types', icon: 'FaUserTie', path: '/admin/hrm/recruitment/interview-types' },
          { title: 'Interview Rounds', icon: 'FaUserTie', path: '/admin/hrm/recruitment/interview-rounds' },
          { title: 'Interviews', icon: 'FaUserTie', path: '/admin/hrm/recruitment/interviews' },
          { title: 'Interview Feedback', icon: 'FaUserTie', path: '/admin/hrm/recruitment/interview-feedback' },
          { title: 'Assessments', icon: 'FaUserTie', path: '/admin/hrm/recruitment/assessments' },
          { title: 'Offer Templates', icon: 'FaUserTie', path: '/admin/hrm/recruitment/offer-templates' },
          { title: 'Offers', icon: 'FaUserTie', path: '/admin/hrm/recruitment/offers' },
          { title: 'Onboarding Checklists', icon: 'FaUserTie', path: '/admin/hrm/recruitment/onboarding-checklists' },
          { title: 'Checklist Items', icon: 'FaUserTie', path: '/admin/hrm/recruitment/checklist-items' },
          { title: 'Candidate Onboarding', icon: 'FaUserTie', path: '/admin/hrm/recruitment/candidate-onboarding' },
        ],
      },
      {
        title: 'Contract Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Contract Types', icon: 'FaUserTie', path: '/admin/hrm/contract-management/contract-types' },
          { title: 'Employee Contracts', icon: 'FaUserTie', path: '/admin/hrm/contract-management/employee-contracts' },
          { title: 'Contract Renewals', icon: 'FaUserTie', path: '/admin/hrm/contract-management/contract-renewals' },
          { title: 'Contract Templates', icon: 'FaUserTie', path: '/admin/hrm/contract-management/contract-templates' },
        ],
      },
      {
        title: 'Document Management',
        icon: 'FaUserTie',
        children: [
          { title: 'Document Categories', icon: 'FaUserTie', path: '/admin/hrm/document-management/document-categories' },
          { title: 'HR Documents', icon: 'FaUserTie', path: '/admin/hrm/document-management/hr-documents' },
          { title: 'Acknowledgments', icon: 'FaUserTie', path: '/admin/hrm/document-management/acknowledgments' },
          { title: 'Document Templates', icon: 'FaUserTie', path: '/admin/hrm/document-management/document-templates' },
        ],
      },
      {
        title: 'Meetings',
        icon: 'FaUserTie',
        children: [
          { title: 'Meeting Types', icon: 'FaUserTie', path: '/admin/hrm/meetings/meeting-types' },
          { title: 'Meeting Rooms', icon: 'FaUserTie', path: '/admin/hrm/meetings/meeting-rooms' },
          { title: 'Meetings', icon: 'FaUserTie', path: '/admin/hrm/meetings/meetings' },
          { title: 'Meeting Attendees', icon: 'FaUserTie', path: '/admin/hrm/meetings/meeting-attendees' },
          { title: 'Meeting Minutes', icon: 'FaUserTie', path: '/admin/hrm/meetings/meeting-minutes' },
          { title: 'Action Items', icon: 'FaUserTie', path: '/admin/hrm/meetings/action-items' },
        ],
      },
      {
        title: 'Calendar',
        icon: 'FaUserTie',
        children: [{ title: 'Calendar Events', icon: 'FaUserTie', path: '/admin/hrm/calendar/calendar-events' }],
      },
      {
        title: 'Media Library',
        icon: 'FaUserTie',
        children: [{ title: 'Media Files', icon: 'FaUserTie', path: '/admin/hrm/media-library/media-files' }],
      },
    ],
  },
  {
    title: 'Accounting',
    icon: 'FaBook',
    path: '/admin/accounting',
    requiredPermissions: ['view-financial-reports', 'view-ledgers', 'view-invoices'],
  },
  { title: 'Projects', icon: 'FaBullseye', path: '/admin/projects' },
  { title: 'Tasks', icon: 'FaBullseye', path: '/admin/tasks' },
  {
    title: 'CRM',
    icon: 'FaHandshake',
    requiredPermissions: ['view-leads', 'view-customers', 'view-crm-reports', 'receive-new-leads'],
    children: [
      { title: 'Dashboard', icon: 'FaTachometerAlt', path: '/admin/crm' },
      { title: 'Customers', icon: 'FaUsers', path: '/admin/crm/customers' },
      { title: 'Team Dashboard', icon: 'FaTachometerAlt', path: '/admin/crm/team-dashboard' },
      { title: 'Lead Assignment', icon: 'FaUsers', path: '/admin/crm/lead-assignment' },
      { title: 'Team Data Collection', icon: 'FaBullseye', path: '/admin/crm/team-data-collection' },
      { title: 'Tier Management', icon: 'FaTachometerAlt', path: '/admin/crm/customer-tier-management' },
      { title: 'Pipeline', icon: 'FaBullseye', path: '/admin/crm/pipeline' },
      { title: 'Tasks', icon: 'FaBullseye', path: '/admin/crm/tasks' },
      { title: 'Analytics', icon: 'FaTachometerAlt', path: '/admin/crm/analytics' },
      { title: 'Quotes', icon: 'FaBook', path: '/admin/crm/quotes' },
      { title: 'Meetings', icon: 'FaUsers', path: '/admin/crm/meetings' },
      { title: 'Emails', icon: 'FaBell', path: '/admin/crm/emails' },
      {
        title: 'Phase 1 Features',
        icon: 'FaCog',
        children: [
          { title: 'Pipeline Settings', icon: 'FaCog', path: '/admin/crm/pipeline-settings' },
          { title: 'Activity Templates', icon: 'FaBullseye', path: '/admin/crm/activity-templates' },
          { title: 'Customer Segments', icon: 'FaUsers', path: '/admin/crm/segments' },
          { title: 'Email Templates', icon: 'FaBell', path: '/admin/crm/email-templates' },
          { title: 'Workflows', icon: 'FaCog', path: '/admin/crm/workflows' },
          { title: 'Quote Templates', icon: 'FaBook', path: '/admin/crm/quote-templates' },
          { title: 'Quote Approvals', icon: 'FaBook', path: '/admin/crm/quote-approvals' },
          { title: 'Sales Forecasts', icon: 'FaTachometerAlt', path: '/admin/crm/forecasts' },
        ],
      },
    ],
  },
  {
    title: 'Telephony',
    icon: 'FaPhone',
    children: [
      { title: 'PBX Call Logs', icon: 'FaPhone', path: '/admin/telephony/calls' },
      { title: 'Reports', icon: 'FaChartBar', path: '/admin/telephony/reports' },
      { title: 'Agent Dashboard', icon: 'FaPhone', path: '/admin/crm/agent-dashboard' },
    ],
  },
  {
    title: 'Support',
    icon: 'FaHeadset',
    path: '/admin/support',
    requiredPermissions: ['view-users', 'view-system-settings'],
  },
  {
    title: 'Users',
    icon: 'FaUser',
    children: [
      { title: 'Manage Users', icon: 'FaUser', path: '/admin/users', requiredPermissions: ['view-users'] },
      { title: 'Assign Roles', icon: 'FaUser', path: '/admin/users/roles', requiredPermissions: ['assign-roles'] },
      { title: 'Role Permissions', icon: 'FaUser', path: '/admin/users/permissions', requiredPermissions: ['assign-roles'] },
    ],
  },
  { title: 'Profile', icon: 'FaUser', path: '/admin/profile' },
  {
    title: 'Settings',
    icon: 'FaCog',
    requiredPermissions: ['manage-system-settings', 'view-system-settings'],
    children: [
      { title: 'Courier Configuration', icon: 'FaCog', path: '/admin/settings/courier-configuration' },
      {
        title: 'Manage Modules',
        icon: 'FaCog',
        path: '/admin/settings/manage-modules',
        requiredPermissions: ['manage-system-settings'],
      },
    ],
  },
];
